### ISSUE TITLE
Remove game from session

### ISSUE THREAD

**Issue by buzzedword** [karl-run/among-us-stats#9]
**Is your feature request related to a problem? Please describe.**
Sometimes we start a new session expecting to be able to start the game, only to have people drop out before it starts. We're left with an incomplete game in our session, which shows an incomplete game in all corresponding rollups.

**Describe the solution you'd like**
I'd like to be able to remove a game from a session.

**Additional context**
![image](https://user-images.githubusercontent.com/334485/107825662-840aa200-6d51-11eb-8bd2-4170afc27dd2.png)
![image](https://user-images.githubusercontent.com/334485/107825664-87059280-6d51-11eb-91fa-53a8f4814171.png)

**Comment by karl-run** [comment]
That's a good suggestion. :) I'll see what I can do!

**Comment by karl-run** [comment]
Sorry about the slow turn around. But I have added this feature for you. Just hover over the game header and you'll see a kebab-menu you can delete the game from.

**Comment by buzzedword** [comment]
Awesome!
